// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.1 (Build Build 350 03/24/2010)
// Created on Wed Nov 07 18:20:25 2012

disp_x_token disp_x_token_inst
(
	.num_token(num_token_sig) ,	// input [3:0] num_token_sig
	.start(start_sig) ,	// input  start_sig
	.clock(clock_sig) ,	// input  clock_sig
	.reset(reset_sig) ,	// input  reset_sig
	.mtne_mode(mtne_mode_sig) ,	// input  mtne_mode_sig
	.mtne_pos(mtne_pos_sig) ,	// input [7:0] mtne_pos_sig
	.pwm_out(pwm_out_sig) ,	// output  pwm_out_sig
	.done(done_sig) ,	// output  done_sig
	.state_out(state_out_sig) 	// output [2:0] state_out_sig
);

defparam disp_x_token_inst.wait_cyles = 'b000000000010;
defparam disp_x_token_inst.servo_out = 'b11111111;
defparam disp_x_token_inst.servo_in = 'b00000001;
